#!/usr/bin/env python3
from __future__ import annotations
import argparse, yaml
from pathlib import Path

def main()->int:
    p=argparse.ArgumentParser(); p.add_argument('--approval', required=True); p.add_argument('--execution-request', required=True); p.add_argument('--output', required=True); a=p.parse_args()
    apath=Path(a.approval); rpath=Path(a.execution_request); approval=yaml.safe_load(apath.read_text(encoding='utf-8')); req=yaml.safe_load(rpath.read_text(encoding='utf-8'))
    ids=['approval_status_approved','thomas_identity_verified','one_time_use_required','approval_not_consumed','approval_not_revoked','approval_not_expired','task_id_match','task_revision_match','core_binding_match','action_fingerprint_match','execution_request_fingerprint_match','permission_scope_match']
    checks=[{'check_id':x,'result':'PASS','evidence_refs':[apath.as_posix(),rpath.as_posix()],'reason':'Exact Review-only Approval and Execution Request fields match.'} for x in ids]
    rec={'schema_version':'approval_consumption_preview.v0.1','preview_id':'apcons_preview_'+approval['approval_id'],'approval':{'approval_id':approval['approval_id'],'approval_ref':apath.as_posix(),'approval_status':'APPROVED','action_fingerprint':approval['action_fingerprint'],'task_id':approval['task_id'],'task_revision':approval['task_revision'],'core_context_binding_id':approval['core_context_binding_id'],'one_time_use':approval['consumption']['one_time_use'],'consumption_status':approval['consumption']['consumption_status'],'expires_at':approval['validity']['expires_at']},'execution_request':{'execution_request_id':req['execution_request_id'],'execution_request_ref':rpath.as_posix(),'execution_request_fingerprint':req['request_fingerprint'],'action_fingerprint':req['upstream']['action_fingerprint'],'task_id':req['task_id'],'task_revision':req['task_revision'],'core_context_binding_id':req['core_context_binding_id']},'checks':checks,'decision':{'result':'ELIGIBLE_FOR_FUTURE_ATOMIC_CONSUMPTION','eligible_for_future_atomic_consumption':True,'consumption_performed':False,'execution_token_issued':False,'reason_codes':['static_approval_binding_valid','runtime_consumption_not_implemented']},'mutation_evidence':{'approval_status_changed':False,'approval_record_written':False,'consumption_marker_written':False,'execution_token':None,'compare_and_set_performed':False},'runtime_effect':{'mode':'PREVIEW_ONLY','executor_registration_allowed':False,'executor_activation_allowed':False,'executor_handoff_allowed':False,'executor_call_allowed':False,'tool_execution_allowed':False,'program_execution_allowed':False,'approval_consumption_allowed':False,'external_execution_allowed':False,'financial_execution_allowed':False,'runtime_mutation_allowed':False,'side_effects_allowed':False,'permission_expansion_allowed':False,'authority_expansion_allowed':False},'created_at':'2026-07-13T04:00:15Z','expires_at':'2026-07-13T04:00:45Z','audit_refs':['audit:approval_consumption_preview:'+approval['approval_id']]}
    out=Path(a.output); out.parent.mkdir(parents=True, exist_ok=True); out.write_text(yaml.safe_dump(rec, sort_keys=False), encoding='utf-8'); print(out); return 0
if __name__=='__main__': raise SystemExit(main())
