#!/usr/bin/env python3
from __future__ import annotations
import argparse, yaml, hashlib
from pathlib import Path
from lib.executor_foundation import compute_rollback_plan_fingerprint

def main()->int:
    p=argparse.ArgumentParser(); p.add_argument('--execution-request', required=True); p.add_argument('--output', required=True); a=p.parse_args(); rp=Path(a.execution_request); req=yaml.safe_load(rp.read_text(encoding='utf-8'))
    rb=[{'step_id':'rollback_01','sequence':1,'action':'restore_pre_action_checkpoint','target_ref':req['execution_plan']['target_ref'],'expected_result':'pre_action_state_restored','requires_approval':True}]
    rc=[{'step_id':'recovery_01','sequence':1,'action':'verify_target_and_lineage_consistency','target_ref':req['execution_plan']['target_ref'],'expected_result':'target_and_lineage_consistent','requires_approval':False}]
    payload={'execution_request_id':req['execution_request_id'],'execution_request_fingerprint':req['request_fingerprint'],'action_fingerprint':req['upstream']['action_fingerprint'],'rollback_required':True,'risk_class':'HIGH','reversibility':'FULL','checkpoint_refs':['checkpoint:'+req['execution_request_id']+':pre-action'],'rollback_steps':rb,'recovery_steps':rc,'recovery_owner':'thomas_prime','recovery_time_objective_seconds':900,'max_data_loss_seconds':0}
    rec={'schema_version':'rollback_recovery_plan.v0.1','plan_id':'rrplan_'+req['execution_request_id'],'execution_request':{'execution_request_id':req['execution_request_id'],'execution_request_ref':rp.as_posix(),'execution_request_fingerprint':req['request_fingerprint'],'action_fingerprint':req['upstream']['action_fingerprint']},'classification':{'rollback_required':True,'risk_class':'HIGH','reversibility':'FULL','reason':'Future durable-state execution requires a checkpointed restoration plan.'},'checkpoint':{'checkpoint_required':True,'checkpoint_available':True,'checkpoint_refs':payload['checkpoint_refs'],'checkpoint_hashes':['sha256:'+hashlib.sha256(req['request_fingerprint'].encode()).hexdigest()],'checkpoint_created_by_execution':False},'rollback':{'steps':rb,'verification_criteria':['pre_action_state_hash_matches_checkpoint','no_partial_runtime_mutation_remains'],'automatic_rollback_allowed':False,'rollback_performed':False},'recovery':{'steps':rc,'owner':'thomas_prime','recovery_time_objective_seconds':900,'max_data_loss_seconds':0,'escalation_target':'thomas_prime','recovery_performed':False},'validation':{'dry_run_status':'NOT_RUN','independent_review_required':True,'independent_review_status':'PENDING','plan_complete':True,'limitations':['No Runtime rollback adapter exists in I0.4.5.']},'plan_fingerprint_payload':payload,'plan_fingerprint':compute_rollback_plan_fingerprint(payload),'runtime_effect':{'mode':'REVIEW_ONLY','executor_registration_allowed':False,'executor_activation_allowed':False,'executor_handoff_allowed':False,'executor_call_allowed':False,'tool_execution_allowed':False,'program_execution_allowed':False,'approval_consumption_allowed':False,'external_execution_allowed':False,'financial_execution_allowed':False,'runtime_mutation_allowed':False,'side_effects_allowed':False,'permission_expansion_allowed':False,'authority_expansion_allowed':False},'lifecycle':{'status':'REVIEW_READY','created_at':'2026-07-13T04:00:00Z','expires_at':'2026-07-14T04:00:00Z','supersedes':[]},'audit_refs':['audit:rollback_recovery_plan:'+req['execution_request_id']]}
    out=Path(a.output); out.parent.mkdir(parents=True, exist_ok=True); out.write_text(yaml.safe_dump(rec, sort_keys=False), encoding='utf-8'); print(out); return 0
if __name__=='__main__': raise SystemExit(main())
